# Generated by Django 3.2 on 2021-05-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerealimage',
            name='image',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
