# Generated by Django 3.2.2 on 2021-05-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cereal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tableCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CerealAmount', models.IntegerField()),
                ('IdCereal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cereal.cereal')),
            ],
        ),
    ]
